edu.unibo.bertopic: # {group_id}.{name} from the knime.yml
  #src: /Users/helfrich/Downloads/knime-bertopic # Path to folder containing the extension files
  #conda_env_path: /Users/helfrich/Downloads/knime-bertopic/.pixi/envs/default # Path to the Python environment to use (use an absolute path)
  #debug_mode: false # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform

  src: C:/Users/Alberto/Documents/GitHub/knime-bertopic # Path to folder containing the extension files
  conda_env_path: C:/Users/Alberto/Documents/GitHub/knime-bertopic/.pixi/envs/default # Path to the Python environment to use (use an absolute path)
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform